export const windowTerms = [
  "double glazing",
  "double glazed",
  "triple glazing",
  "triple glazed",
  "single glazing",
  "single glazed",
  "secondary glazing",
  "secondary glazed",
  "uPVC",
  "timber frames",
  "aluminium frames",
  "sealed units",
  "glazing replacement",
  "window replacement",
  "window installation",
  "window repair",
  "window maintenance",
  "window cleaning",
];

export const accessibilityTerms = [
  "step-free access to property",
  "wheelchair accessible parking",
  "level access throughout property",
  "wet room within property",
  "step-free access into garden",
  "disabled access",
  "disabled friendly",
];

export const buildingSafetyTermsPositive = [
  "structural integrity",
  "fire safety",
  "safety certificate",
  "code compliance",
  "EWS1",
  "building regulations",
  "fire escape",
  "emergency exit",
  "fire alarm system",
  "smoke detectors",
  "carbon monoxide detectors",
  "fire doors",
  "sprinkler system",
  "fire extinguishers",
  "safety inspection",
  "building survey",
  "structural survey",
  "foundation integrity",
  "roof integrity",
  "electrical safety",
  "gas safety",
  "emergency lighting",
  "fireproof materials",
  "fire-resistant doors",
  "fire-resistant walls",
  "fire-resistant floors",
  "fire-resistant ceilings",
  "fire-resistant windows",
  "fire-resistant cladding",
  "fire-resistant insulation",
  "fire-resistant roofing",
  "fire-resistant paint",
  "fire-resistant sealants",
  "fire-resistant barriers",
  "fire-resistant partitions",
  "fire-resistant glazing",
  "fire-resistant ductwork",
  "fire-resistant cables",
  "fire-resistant conduits",
  "fire-resistant pipes",
  "fire-resistant joints",
  "fire-resistant coatings",
  "fire-resistant systems",
  "fire-resistant materials",
  "fire-resistant construction",
  "fire-resistant design",
  "fire-resistant installation",
  "fire-resistant maintenance",
  "fire-resistant inspection",
  "fire escape",
  "emergency exit",
  "fire alarm system",
  "smoke detectors",
  "carbon monoxide detectors",
  "fire doors",
  "sprinkler system",
  "fire extinguishers",
];

export const buildingSafetyTermsNegative = [
  "mould",
  "damp",
  "asbestos",
  "radon testing",
  "building survey",
  "structural survey",
  "foundation survey",
  "roof survey",
  "electrical survey",
  "gas survey",
  "emergency lighting survey",
  "EWS1",
  "building regulations",
  "safety inspection",
  "building survey",
  "structural survey",
];

export const coastalErosionTermsPositive = [
  "coastal protection",
  "coastal defence",
  "erosion control",
  "erosion management",
  "coastal zone management",
  "coastal monitoring",
  "coastal zone protection",
  "coastal zone management plan",
  "coastal zone monitoring",
  "coastal zone defence",
  "coastal zone control",
];

export const coastalErosionTermsNegative = [
  "coastal erosion",
  "sea erosion",
  "shoreline erosion",
  "beach erosion",
  "coastal erosion risk",
  "coastal erosion damage",
  "coastal erosion prevention",
  "coastal erosion mitigation",
  "coastal erosion repair",
  "coastal erosion warning",
  "coastal erosion risk assessment",
  "cliff erosion",
  "coastal retreat",
  "coastal land loss",
  "shoreline retreat",
  "beach loss",
  "sea level rise",
  "storm surge",
  "wave action",
  "tidal erosion",
  "coastal flooding",
  "coastal hazard",
  "coastal vulnerability",
  "coastal impact",
  "coastal hazard assessment",
  "coastal vulnerability assessment",
  "coastal impact assessment",
  "coastal zone risk",
  "coastal area",
  "coastal zone",
  "coastal region",
  "coastal location",
  "coastal vicinity",
  "coastal neighbourhood",
  "coastal community",
  "coastal town",
  "coastal village",
  "coastal city",
  "coastal property",
  "coastal home",
  "coastal residence",
  "coastal living",
  "coastal environment",
  "coastal access",
];
