export const STEPS = {
  INITIAL_REVIEW: "INITIAL_REVIEW",
  SELECT_ISSUES: "SELECT_ISSUES",
  RIGHTMOVE_SIGN_IN: "RIGHTMOVE_SIGN_IN",
  REVIEW_MESSAGE: "REVIEW_MESSAGE",
  EMAIL_SENT: "EMAIL_SENT",
} as const;
